export const spojniceCombDb = [
  {
    title:"SPOJITE GRADOVE SA SVOJIM NEKADAŠNJIM NAZIVIMA",
    set: [
      { id: 1, name: "Beograd" },
      { id: 1, name: "Singidunum" },
      { id: 2, name: "Sremska Mitrovica" },
      { id: 2, name: "Sirmijum" },
      { id: 3, name: "Džakarta" },
      { id: 3, name: "Batavija" },
      { id: 4, name: "Knjaževac" },
      { id: 4, name: "Gurgusovac" },
      { id: 5, name: "Jagodina" },
      { id: 5, name: "Svetozarevo" },
      { id: 6, name: "Njujork" },
      { id: 6, name: "Novi Amsterdam" },  
      { id: 7, name: "Bratislava" },
      { id: 7, name: "Presburg" },
      { id: 8, name: "Podgorica" },
      { id: 8, name: "Titograd" },
    ],
  },
  {
    title:"SPOJITI SRPSKE VOJSKOVOĐE SA MESTOM ROĐENJA",
    set: [
      { id: 1, name: "Hajduk Veljko" },
      { id: 1, name: "Lenovac" },
      { id: 2, name: "Stanoje Glavaš" },
      { id: 2, name: "Glibovac" },
      { id: 3, name: "Vuk Isaković" },
      { id: 3, name: "Sredska" },
      { id: 4, name: "Karađorđe Petrović" },
      { id: 4, name: "Viševac" },
      { id: 5, name: "Stojan Čupić" },
      { id: 5, name: "Piva" },
      { id: 6, name: "Vasa Čarapić" },
      { id: 6, name: "Beli Potok" },
      { id: 7, name: "Lazar Hrebaljanović" },
      { id: 7, name: "Prilepac" },
      { id: 8, name: "Petar Dobrnjac" },
      { id: 8, name: "Dobrinje" },
    ],
  },
  {
    title:"POVEŽITE POZNATE LIČNOSTI SA IMENIMA NJIHOVIH KONJA",
    set: [
      { id: 1, name: "Banović Strahinja" },
      { id: 1, name: "Đogin" },
      { id: 2, name: "Vojvoda Momčilo" },
      { id: 2, name: "Jabučilo" },
      { id: 3, name: "Damjan" },
      { id: 3, name: "Zelenko" },
      { id: 4, name: "Aleksandar Makedonski" },
      { id: 4, name: "Bukefal" },
      { id: 5, name: "Vajat Erp" },
      { id: 5, name: "Dik Hejlor" },
      { id: 6, name: "Bik Koji Sedi" },
      { id: 6, name: "Bleki" },
      { id: 7, name: "Napoleon" },
      { id: 7, name: "Marengo" },
      { id: 8, name: "Simon Bolivar" },
      { id: 8, name: "Palomo" },
    ],
  },
];
