export const spojniceCombDb = [
  {
    title:"SPOJITE GRADOVE SA SVOJIM NEKADAŠNJIM NAZIVIMA",
    set: [
      { id: 1, name: "Beograd" },
      { id: 1, name: "Singidunum" },
      { id: 2, name: "Sremska Mitrovica" },
      { id: 2, name: "Sirmijum" },
      { id: 3, name: "Džakarta" },
      { id: 3, name: "Batavija" },
      { id: 4, name: "Knjaževac" },
      { id: 4, name: "Gurgusovac" },
      { id: 5, name: "Jagodina" },
      { id: 5, name: "Svetozarevo" },
      { id: 6, name: "Njujork" },
      { id: 6, name: "Novi Amsterdam" },  
      { id: 7, name: "Bratislava" },
      { id: 7, name: "Presburg" },
      { id: 8, name: "Podgorica" },
      { id: 8, name: "Titograd" },
    ],
  },
  {
    title:"SPOJITI SRPSKE VOJSKOVOĐE SA MESTOM ROĐENJA",
    set: [
      { id: 1, name: "Hajduk Veljko" },
      { id: 1, name: "Lenovac" },
      { id: 2, name: "Stanoje Glavaš" },
      { id: 2, name: "Glibovac" },
      { id: 3, name: "Vuk Isaković" },
      { id: 3, name: "Sredska" },
      { id: 4, name: "Karađorđe Petrović" },
      { id: 4, name: "Viševac" },
      { id: 5, name: "Stojan Čupić" },
      { id: 5, name: "Piva" },
      { id: 6, name: "Vasa Čarapić" },
      { id: 6, name: "Beli Potok" },
      { id: 7, name: "Lazar Hrebaljanović" },
      { id: 7, name: "Prilepac" },
      { id: 8, name: "Petar Dobrnjac" },
      { id: 8, name: "Dobrinje" },
    ],
  },
  {
    title:"POVEŽITE POZNATE LIČNOSTI SA IMENIMA NJIHOVIH KONJA",
    set: [
      { id: 1, name: "Banović Strahinja" },
      { id: 1, name: "Đogin" },
      { id: 2, name: "Vojvoda Momčilo" },
      { id: 2, name: "Jabučilo" },
      { id: 3, name: "Damjan" },
      { id: 3, name: "Zelenko" },
      { id: 4, name: "Aleksandar Makedonski" },
      { id: 4, name: "Bukefal" },
      { id: 5, name: "Vajat Erp" },
      { id: 5, name: "Dik Hejlor" },
      { id: 6, name: "Bik Koji Sedi" },
      { id: 6, name: "Bleki" },
      { id: 7, name: "Napoleon" },
      { id: 7, name: "Marengo" },
      { id: 8, name: "Simon Bolivar" },
      { id: 8, name: "Palomo" },
    ],
  },
  {
    "title": "POVEŽITE MINISTRE SA NJIHOVIM MINISTARSTVIMA U VLADI MIRKA CVETKOVIĆA",
    "set": [
      { "id": 1, "name": "Unutrašnji poslovi" },
      { "id": 1, "name": "Ivica Dačić" },
      { "id": 2, "name": "Finansije" },
      { "id": 2, "name": "Dijana Dragutinović" },
      { "id": 3, "name": "Ministarstvo pravde" },
      { "id": 3, "name": "Snežana Malović" },
      { "id": 4, "name": "Rudarstvo i energetika" },
      { "id": 4, "name": "Petar Škundrić" },
      { "id": 5, "name": "Zdravlje" },
      { "id": 5, "name": "Tomica Milosavljević" },
      { "id": 6, "name": "Ministar bez portfelja" },
      { "id": 6, "name": "Sulejman Ugljanin" },
      { "id": 7, "name": "Kosovo i Metohija" },
      { "id": 7, "name": "Goran Bogdanović" },
      { "id": 8, "name": "Infrastruktura" },
      { "id": 8, "name": "Milutin Mrkonjić" }
    ]
  },{
    "title": "POVEŽITE MINISTRE SA NJIHOVIM MINISTARSTVIMA U VLADI MIRKA CVETKOVIĆA",
    "set": [
      { "id": 1, "name": "Unutrašnji poslovi" },
      { "id": 1, "name": "Ivica Dačić" },
      { "id": 2, "name": "Finansije" },
      { "id": 2, "name": "Dijana Dragutinović" },
      { "id": 3, "name": "Ministarstvo pravde" },
      { "id": 3, "name": "Snežana Malović" },
      { "id": 4, "name": "Rudarstvo i energetika" },
      { "id": 4, "name": "Petar Škundrić" },
      { "id": 5, "name": "Zdravlje" },
      { "id": 5, "name": "Tomica Milosavljević" },
      { "id": 6, "name": "Ministar bez portfelja" },
      { "id": 6, "name": "Sulejman Ugljanin" },
      { "id": 7, "name": "Kosovo i Metohija" },
      { "id": 7, "name": "Goran Bogdanović" },
      { "id": 8, "name": "Infrastruktura" },
      { "id": 8, "name": "Milutin Mrkonjić" }
    ]
  },
  {
    "title": "SPOJITE NOVČANICE SA OSOBAMA ČIJI SE LIKOVI NALAZE NA NJIMA",
    "set": [
      { "id": 1, "name": "10 RSD" },
      { "id": 1, "name": "Vuk Karadžić" },
      { "id": 2, "name": "1 USD" },
      { "id": 2, "name": "Džordž Vašington" },
      { "id": 3, "name": "5000 RSD" },
      { "id": 3, "name": "Slobodan Jovanović" },
      { "id": 4, "name": "5 USD" },
      { "id": 4, "name": "Abraham Linkoln" },
      { "id": 5, "name": "10 GBP" },
      { "id": 5, "name": "Čarls Darvin" },
      { "id": 6, "name": "50 RSD" },
      { "id": 6, "name": "Stevan Mokranjac" },
      { "id": 7, "name": "20 USD" },
      { "id": 7, "name": "Endrju Džekson" },
      { "id": 8, "name": "200 RSD" },
      { "id": 8, "name": "Nadežda Petrović" }
    ]
  },
  {
    "title": "SPOJITE GODINE SA DRŽAVAMA KOJE SU IH UVELE",
    "set": [
      { "id": 1, "name": "1968." },
      { "id": 1, "name": "Italija" },
      { "id": 2, "name": "2004." },
      { "id": 2, "name": "Grčka" },
      { "id": 3, "name": "1964." },
      { "id": 3, "name": "Španija" },
      { "id": 4, "name": "1976." },
      { "id": 4, "name": "Čehoslovačka (Češka)" },
      { "id": 5, "name": "2000." },
      { "id": 5, "name": "Francuska" },
      { "id": 6, "name": "1960." },
      { "id": 6, "name": "SSSR (Rusija)" },
      { "id": 7, "name": "1988." },
      { "id": 7, "name": "Holandija" },
      { "id": 8, "name": "1992." },
      { "id": 8, "name": "Danska" }
    ]
  },
  {
    "title": "SPOJITE BROJEVE SA NJIHOVIM NAJMANJIM ZAJEDNIČKIM SADRŽAOCEM",
    "set": [
      { "id": 1, "name": "5 i 3" },
      { "id": 1, "name": "15" },
      { "id": 2, "name": "4 i 8" },
      { "id": 2, "name": "8" },
      { "id": 3, "name": "2 i 5" },
      { "id": 3, "name": "10" },
      { "id": 4, "name": "2 i 9" },
      { "id": 4, "name": "18" },
      { "id": 5, "name": "4 i 5" },
      { "id": 5, "name": "20" },
      { "id": 6, "name": "6 i 8" },
      { "id": 6, "name": "24" },
      { "id": 7, "name": "4 i 6" },
      { "id": 7, "name": "12" },
      { "id": 8, "name": "7 i 3" },
      { "id": 8, "name": "21" }
    ]
  },
  {
    "title": "SPOJITE POZIVNE BROJEVE SA DRŽAVAMA KOJIMA PRIPADAJU",
    "set": [
      { "id": 1, "name": "34" },
      { "id": 1, "name": "Španija" },
      { "id": 2, "name": "7" },
      { "id": 2, "name": "Rusija" },
      { "id": 3, "name": "44" },
      { "id": 3, "name": "Engleska" },
      { "id": 4, "name": "32" },
      { "id": 4, "name": "Belgija" },
      { "id": 5, "name": "46" },
      { "id": 5, "name": "Švedska" },
      { "id": 6, "name": "359" },
      { "id": 6, "name": "Bugarska" },
      { "id": 7, "name": "39" },
      { "id": 7, "name": "Italija" },
      { "id": 8, "name": "420" },
      { "id": 8, "name": "Češka" }
    ]
  },
  {
    "title": "SPOJITE PROIZVOĐAČE AUTOMOBILA SA NJIHOVIM MODELIMA",
    "set": [
      { "id": 1, "name": "Renault" },
      { "id": 1, "name": "Espace" },
      { "id": 2, "name": "Opel" },
      { "id": 2, "name": "Insignia" },
      { "id": 3, "name": "Hyundai" },
      { "id": 3, "name": "I 30" },
      { "id": 4, "name": "Fiat" },
      { "id": 4, "name": "Linea" },
      { "id": 5, "name": "Honda" },
      { "id": 5, "name": "Legend" },
      { "id": 6, "name": "Chevrolet" },
      { "id": 6, "name": "Orlando" },
      { "id": 7, "name": "Toyota" },
      { "id": 7, "name": "Corolla" },
      { "id": 8, "name": "Peugeot" },
      { "id": 8, "name": "407" }
    ]
  },
  {
    "title": "SPOJITE PISCE SA SVOJIM DELIMA",
    "set": [
      { "id": 1, "name": "Onore de Balzak" },
      { "id": 1, "name": "Ljiljan u dolu" },
      { "id": 2, "name": "Šarl Bodler" },
      { "id": 2, "name": "Cveće zla" },
      { "id": 3, "name": "Emile Zola" },
      { "id": 3, "name": "U ključalom loncu" },
      { "id": 4, "name": "Dositej Obradović" },
      { "id": 4, "name": "Ljubezni haralampijr" },
      { "id": 5, "name": "Antun Gustav Matoš" },
      { "id": 5, "name": "Oko lobora" },
      { "id": 6, "name": "Žak Prever" },
      { "id": 6, "name": "Sunce noći" },
      { "id": 7, "name": "Stevan Sremac" },
      { "id": 7, "name": "Ibiš-aga" },
      { "id": 8, "name": "Aleksandar Puškin" },
      { "id": 8, "name": "Braća razbojnici" }
    ]
  },
  {
    "title": "SPOJITE BAJKU SA AUTOROM",
    "set": [
      { "id": 1, "name": "Mala sirena" },
      { "id": 1, "name": "Hans Kristijan Andersen" },
      { "id": 2, "name": "Pinokio" },
      { "id": 2, "name": "Karlo Kolodi" },
      { "id": 3, "name": "Tri praseta" },
      { "id": 3, "name": "Jozef Jakobs" },
      { "id": 4, "name": "Zlatokosa" },
      { "id": 4, "name": "Braća Grim" },
      { "id": 5, "name": "Crvenkapa" },
      { "id": 5, "name": "Šarl Pero" },
      { "id": 6, "name": "Princeza i žabac" },
      { "id": 6, "name": "Aleksandar Afanasjev" },
      { "id": 7, "name": "Baš Čelik" },
      { "id": 7, "name": "Vuk Karadžić" },
      { "id": 8, "name": "Tri medveda" },
      { "id": 8, "name": "Robert Souti" }
    ]
  },
  {
    title: "SPOJITE SKRAĆENICE SA DRŽAVAMA",
    set: [
      { id: 1, name: "A" },
      { id: 1, name: "AUSTRIJA" },
      { id: 2, name: "AUS" },
      { id: 2, name: "AUSTRALIJA" },
      { id: 3, name: "GR" },
      { id: 3, name: "GRCKA" },
      { id: 4, name: "D" },
      { id: 4, name: "NEMACKA" },
      { id: 5, name: "GE" },
      { id: 5, name: "GRUZIJA" },
      { id: 6, name: "IRL" },
      { id: 6, name: "IRSKA" },
      { id: 7, name: "IR" },
      { id: 7, name: "IRAN" },
      { id: 8, name: "I" },
      { id: 8, name: "ITALIJA" },
    ],
  },
  {
    title: "SPOJITE ZALIVE SA MORIMA I OKEANIMA",
    set: [
      { id: 1, name: "AKAPSKI ZALIV" },
      { id: 1, name: "CRVENO MORE" },
      { id: 2, name: "ANADIRSKI ZALIV" },
      { id: 2, name: "BERINGOVO MORE" },
      { id: 3, name: "BOTNIJSKI ZALIV" },
      { id: 3, name: "BALTICKO MORE" },
      { id: 4, name: "KASTELANSKI ZALIV" },
      { id: 4, name: "JADRANSKO MORE" },
      { id: 5, name: "PERSIJSKI ZALIV" },
      { id: 5, name: "INDIJSKI OKEAN" },
      { id: 6, name: "ZALIV FANDI" },
      { id: 6, name: "ATLANSKI OKEAN" },
      { id: 7, name: "ZALIV HADSON" },
      { id: 7, name: "SEVERNI LEDENI OKEAN" },
      { id: 8, name: "ALJASKI ZALIV" },
      { id: 8, name: "TIHI OKEAN" },
    ],
  },{
    title: "SPOJITE FUDBALSKE KLUBOVE SA GRADOVIMA",
    set: [
      { id: 1, name: "ASTON VILA" },
      { id: 1, name: "BIRMINGEM" },
      { id: 2, name: "EVERTON" },
      { id: 2, name: "LIVERPUL" },
      { id: 3, name: "JUVENTUS" },
      { id: 3, name: "TORINO" },
      { id: 4, name: "LEVANTE" },
      { id: 4, name: "VALENSIJA" },
      { id: 5, name: "ESPANJOL" },
      { id: 5, name: "BARSELONA" },
      { id: 6, name: "TOTENHEM" },
      { id: 6, name: "LONDON" },
      { id: 7, name: "SPARTA" },
      { id: 7, name: "ROTERDAM" },
      { id: 8, name: "RAPID" },
      { id: 8, name: "BEC" },
    ],
  } ,{
    title: "SPOJITE POZNATE LIČNOSTI SA NJIHOVIM PROFESIJAMA",
    set: [
      { id: 1, name: "PEVACICA" },
      { id: 1, name: "MILICA MAJSTOROVIC" },
      { id: 2, name: "RUKOMETAS" },
      { id: 2, name: "IGOR BUTULIJA" },
      { id: 3, name: "MODNI KREATOR" },
      { id: 3, name: "VERICA RAKOCEVIC" },
      { id: 4, name: "FUDBALER" },
      { id: 4, name: "NEMANJA VIDIC" },
      { id: 5, name: "POLITICAR" },
      { id: 5, name: "IVICA DACIC" },
      { id: 6, name: "MANEKENKA" },
      { id: 6, name: "TIJANA STAJSIC" },
      { id: 7, name: "GLUMICA" },
      { id: 7, name: "ANA VILENICA" },
      { id: 8, name: "VODITELJ" },
      { id: 8, name: "DRAGAN MARINKOVIC" },
    ],
  },{
    title: "SPOJITE FILMOVE SA GODINAMA IZLASKA",
    set: [
      { id: 1, name: "KUM" },
      { id: 1, name: "1972" },
      { id: 2, name: "BLISTAVI UM" },
      { id: 2, name: "2001" },
      { id: 3, name: "SINDLEROVA LISTA" },
      { id: 3, name: "1993" },
      { id: 4, name: "PLES SA VUKOVIMA" },
      { id: 4, name: "1990" },
      { id: 5, name: "POSLEDNJI KINESKI CAR" },
      { id: 5, name: "1987" },
      { id: 6, name: "ENGLESKI PACIJENT" },
      { id: 6, name: "1996" },
      { id: 7, name: "ROKI" },
      { id: 7, name: "1976" },
      { id: 8, name: "MILIONER IZ BLATA" },
      { id: 8, name: "2008" },
    ],
  }
];
